---
date: 2022-05-17
aliases: []
---
# 處理錯誤
## `try {} catch(err) {}`
try catch 可檢查一般的JS程式碼錯誤，若在try區塊發生錯誤時，會將錯誤訊息傳至catch，如:
```js
const i = 1;
try {
  i = 2;
} catch(err) {
  console.log(err);
}
```

## throw
throw 可自訂錯誤行為，丟出自訂錯誤訊息給 catch
```js
let message = document.getElementByID('input').value;
try {
  if (message.length > 10) {
    throw "Too long."
  } else if (message.length == 0) {
    throw "Please keyin something."
  }
} catch(err) {
  console.log(err);
}
```
throw 不只可丟出字串，也可丟出任意型態值或是Error物件

## finally
無論執行 try 或 catch ，最終皆會執行 finally
```js
let message = document.getElementByID('input').value;
try {
  if (message.length > 10) {
    throw "Too long."
  } else if (message.length == 0) {
    throw "Please keyin something."
  }
} catch(err) {
  console.log(err);
} finally {
  message = "";
}
```